<?php

app('xe.pluginRegister')->addComponents([
    App\UIObjects\Captcha\CaptchaUIObject::class,
    App\Skins\Error\DefaultErrorSkin::class,
    App\UIObjects\Menu\MenuType::class,
    App\UIObjects\Menu\MenuSelect::class,
    App\UIObjects\Menu\TypeSelect::class,
    Xpressengine\Menu\MenuType\DirectLink::class,
    App\UIObjects\Permission\Permission::class,
    Xpressengine\Editor\Textarea::class,
    App\UIObjects\Form\Form::class,
    App\UIObjects\Form\FormCheckbox::class,
    App\UIObjects\Form\FormFile::class,
    App\UIObjects\Form\FormImage::class,
    App\UIObjects\Form\FormLangText::class,
    App\UIObjects\Form\FormLangTextArea::class,
    App\UIObjects\Form\FormPassword::class,
    App\UIObjects\Form\FormSelect::class,
    App\UIObjects\Form\FormText::class,
    App\UIObjects\Form\FormTextArea::class,
    App\UIObjects\Form\FormColorpicker::class,
    App\UIObjects\Lang\LangText::class,
    App\UIObjects\Lang\LangTextArea::class,
    App\UIObjects\Member\ProfileBgImage::class,
    App\UIObjects\Member\ProfileImage::class,
    App\Skins\Plugin\PluginSettingsSkin::class,
    App\UIObjects\Settings\SettingsPermission::class,
    App\Themes\SettingsTheme::class,
    App\UIObjects\Skin\SkinSelect::class,
    config('xe.theme.blank'),
    App\UIObjects\Theme\ThemeSelect::class,
    App\ToggleMenus\User\ProfileItem::class,
    App\ToggleMenus\User\ManageItem::class,
    App\Skins\Member\AuthSkin::class,
    App\Skins\Member\SettingsSkin::class,
    App\Skins\Member\ProfileSkin::class,
    App\Widgets\StorageSpace::class,
    App\Widgets\ContentInfo::class,
    App\Widgets\SystemInfo::class,
    App\Widgets\DownloadRank::class,
    App\Widgets\HtmlWidget::class,
    App\Skins\Widget\SystemInfoSkin::class,
    App\Skins\Widget\ContentInfoSkin::class,
    App\Skins\Widget\DownloadRankSkin::class,
    App\Skins\Widget\HtmlWidgetSkin::class,
    App\Skins\Widget\StorageSpaceSkin::class,
    App\UIObjects\Widget\WidgetGenerator::class,
    App\UIObjects\Widget\WidgetBox::class,
    App\FieldTypes\Email::class,
    App\FieldTypes\Textarea::class,
    App\FieldTypes\Url::class,
    App\FieldTypes\Category::class,
    App\FieldTypes\Number::class,
    App\FieldTypes\Text::class,
    App\FieldTypes\Boolean::class,
    App\FieldTypes\Address::class,
    App\FieldTypes\CellPhoneNumber::class,
    App\FieldSkins\Category\DefaultSkin::class,
    App\FieldSkins\Number\DefaultSkin::class,
    App\FieldSkins\Text\DefaultSkin::class,
    App\FieldSkins\Text\EmailSkin::class,
    App\FieldSkins\Text\UrlSkin::class,
    App\FieldSkins\Boolean\DefaultSkin::class,
    App\FieldSkins\Address\DefaultSkin::class,
    App\FieldSkins\CellPhoneNumber\DefaultSkin::class,
    App\FieldSkins\Textarea\DefaultSkin::class,
    App\FieldSkins\Email\DefaultSkin::class,
    App\FieldSkins\Url\DefaultSkin::class,
]);






